# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - triage
  - important
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Thanks for your issue. This issue has been automatically marked as stale
  because it has not had recent activity. It will be closed in 7 days if 
  there's no further activity.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue has been closed due to inactivity. Please open a new issue 
  if the problem still persists.
