opt_in_rules:
  - toggle_bool
  - modifier_order
  - yoda_condition
  - trailing_closure
  - vertical_parameter_alignment_on_call
  - redundant_nil_coalescing
  - prefer_self_type_over_type_of_self
  - implicit_return
  - indentation_width

disabled_rules:
  - line_length
  - unused_closure_parameter
  - multiple_closures_with_trailing_closure
  - large_tuple
  - todo # This is silly - todos are there for a reason
  - indentation_width # Xcode auto-indentation sometimes uses odd indents which look better than consistent ones

#######################
## Rule configs
#######################

force_cast: warning
force_try: warning

indentation_width:
  include_compiler_directives: false
  include_comments: false
  # Note: Rule is disabled for some wrapped if conditions because they look
  # significantly better at the same level of the parent condition

nesting:
  type_level:
    warning: 4

identifier_name:
  min_length:
    warning: 3
    error: 0
  max_length:
    warning: 40
    error: 50
  allowed_symbols: ["_"]
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
